# Simple Setup
#version: 2
#jobs:
#    build:
#      docker:
#        - image: srcml/ubuntu_x86_64_base
#      steps:
#        - checkout
#        - run: cd my_stl && mkdir build && cd build && cmake ../ -DBUILD_UNIT_TESTS=On && make && make test

# Workflow with build/test
version: 2
jobs: 
    build:
      docker:
        - image: srcml/ubuntu_x86_64_base
      steps:
        - checkout
        - run: mkdir build
        - run: cd build && cmake ../ -DBUILD_UNIT_TESTS=On && make
        - persist_to_workspace:
            root: build
            paths:
              - ./*

    test:
      docker:
        - image: srcml/ubuntu_x86_64_base
      steps:
        - checkout
        - attach_workspace:
            at: build
        - run: cd build && make test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build