# Simple Setup
version: 2
jobs:
    build:
      docker:
        - image: srcml/ubuntu_x86_64_base
      steps:
        - checkout
        - run: cd my_stl && mkdir build && cd build && cmake ../ -DBUILD_UNIT_TESTS=On && make && make test
